#!/usr/bin/env bash

##  Main installation script ##

source argparse

# Example Usage #

# main --username "jared" --password "password" --noconfirm --all --configuration

arg_parse "$@"

echo "Configuration file: $CONFIGURATION"

set -- "${POSITIONAL[@]}" # restore positional arguments

# Before setting alias #

[[ ! -z "${CP+x}" ]] && echo "[ERROR] CP should not be an export"

[[ ! -z "${CONFIGURATION+x}" ]] && source "$CONFIGURATION"

# After setting alias #

echo "$CP"
hello_world

echo "User: $USER_PLAIN"
echo "Password: $PASSWORD_PLAIN"
