#!/usr/bin/env bash

##  Main installation script ##

source argparse
source "arch/components/base_install/base_install"

export LOG_DIR="/tmp/thin_mint_logs"

[[ ! -d "$LOG_DIR" ]] && mkdir "$LOG_DIR"

# Example Usage #

# main --username "jared" --password "password" --configuration configurations/.jaredrc

arg_parse "$@"

# restore positional arguments

[[ ! -z "${CONFIGURATION+x}" ]] && source "$CONFIGURATION"
set -- "${POSITIONAL[@]}"

# base_install_main                                                                      # base_install.base_install_main          [NOTE: BEGIN]

arch-chroot /mnt ./components/base_install/system_configuration                                     # system_configuration.system_configuration_main
#arch-chroot /mnt ./components/desktop_setup/user_configuration                                 # user_configuration.initial_configuration

#arch-chroot /mnt ./tmp/desktop_setup/greeter_configuration                              # greeter_configuration.greeter_conf

#[[ "$DE" == "cinnamon" ]] \
                        #&& arch-chroot /mnt ./tmp/desktop_setup/cinnamon \
                        #|| arch-chroot /mnt ./tmp/desktop_setup/i3


#make_root "$PLAIN_USER"                                                                # user_configuration.make_root
# rm /mnt/components                                                                    # Clean up
#unmount_all_partitions                                                                 # base_install.unmount_all_partitions     [NOTE: END]
