#!/usr/bin/env zsh

# Create Arch ISO image from current installation
# AUTHOR: Jared Dyreson

vared -p "Installer codename: " -c codename

home="$HOME"
project="$home/Projects/thin-mint/arch/components"
new_home=""$codename"/relang/airootfs/etc"
project_conf_dir="$new_home/thin-mint"
current_host="$(hostname)"

# DIRECTORY STRUCTURE

#sudo cp -r /usr/share/archiso/configs/relang/ "$codename"
#mkdir "$new_home"/skel/{Desktop,Documents,Downloads,Music,Pictures/Wallpapers,Videos}
#mkdir "$project_conf_dir"

# SYSTEM CONFIGURATION

#sudo cp -v /etc/{hosts,hostname} "$new_home"
#sudo cp -v /etc/locale.{gen,conf} "$new_home"
#pacman -Qqne > "$codename/relang/packages.x86_64"

# HELPER SCRIPTS

#cp "$project"/base_install/base_install "$project_conf_dir"

# TERMINAL CONFIGURATION

#cp "$home"/{.vimrc,.zshrc} "$new_home"/etc

#
