#!/usr/bin/env bash

function cinnnmon_de() {
    # This is a floating window manager

    declare -a packages=(
        "xorg-server"
        "cinnamon"
        "noto-fonts"
    )

    pacman -Syu

    for package in "${packages[@]}"; do
        pacman -S --noconfirm "$package"
    done
}

function i3_configuration() {
    echo "PLEASE IMPLEMENT ME"
}
