#!/usr/bin/env bash

# Main for all the modules installed

source user_configuration
source user_terminal_conf

# properly dispose of stored username
# unset MINT_PASS

MAKEPKG_DEST="/root/built-packages"
USB_DEST="/run/media/packages"

#[[ ! "$(grep -i "arch" /etc/os-release)" ]] && wrong_os_err_
#[[ "$EUID" -ne 0 ]] && perm_err_

exec 1> >(tee "desktop_stdout.log")
exec 2> >(tee "desktop_stderr.log")

# main list of functions

#initial_configuration
#create_user
#terminal_configuration
