#!/usr/bin/env bash

function greeter_conf() {
    declare -a packages=(
        "lightdm"
        "lightdm-gtk-greeter"
    )

    pacman -Syu

    for package in "${packages[@]}"; do
        pacman -S --noconfirm "$package"
    done

    sed -i 's/#greeter-session=.*/greeter-session=lightdm-slick-greeter/' /etc/lightdm/lightdm.conf
    systemctl enable lightdm.service

    cp -av assets/slick-greeter.conf /etc/lightdm/
    cp -av --no-preserve=mode ../../../wallpapers/VenomWallpaper.jpg /etc/lightdm/
}

