#!/usr/bin/env bash

# Main for all the modules installed

# NOTE: DONE
source user_configuration
source greeter_configuration

initial_configuration # create the base user, along with their file structure

greeter_conf

# remove all mentions of this variable

unset PASSWORD_PLAIN
make_root "$PLAIN_USER"
