#!/usr/bin/env bash

source user_configuration
source turtle

## initial config ##

#mkdir -p "$MINT_HOME"/{Applications,archives,Downloads,Documents,Music,Pictures/Wallpapers,Projects,Video}
#git clone https://github.com/JaredDyreson/dotfiles "$MINT_HOME"/Projects/dotfiles
#git clone https://github.com/JaredDyreson/university "$MINT_HOME"/Projects/university

function themes(){
# WORKS, but needs to install themes and load conf file. we can test if those work later on
	declare -a themes=('mint-x-icons' 'mint-y-icons' 'mint-themes')
	for theme in "${themes[@]}"; do
    echo "$theme"
	done
	mkdir -p "$MINT_HOME"/{.icons,.themes}
	git clone https://github.com/daniruiz/flat-remix "$MINT_HOME"/.icons/
	git clone https://github.com/daniruiz/flat-remix-gtk "$MINT_HOME"/.themes/
  cp -puv "$MINT_HOME"/Projects/dotfiles/wallpaper/* "$MINT_HOME"/Pictures/Wallpapers
  [[ -f "$MINT_HOME"/Projects/dotfiles/desktop_env/arch_linux_settings ]] && echo "arch desktop conf exists"
}

function terminal(){

  #curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | bash
  #cp -v $MINT_HOME/Projects/dotfiles/shell/zshrc "$MINT_HOME"/.zshrc
  #git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $MINT_HOME/zsh-syntax-highlighting
  #return

#######

  #git clone https://github.com/VundleVim/Vundle.vim.git "$MINT_HOME"/.vim/bundle/Vundle.vim
  #cp -v $MINT_HOME/Projects/dotfiles/shell/vimrc $MINT_HOME/.vimrc
  #vim +silent +PluginInstall +qall
########

  cp -v $MINT_HOME/Projects/dotfiles/terminal/Xresources $MINT_HOME/.Xresources
  sed 's/^\!.*//g' "$MINT_HOME"/.Xresources | xrdb

########

  git config --global user.name "Jared Dyreson"
  git config --global user.email "jared.dyreson@gmail.com"
#########
}

function 

