#!/usr/bin/env bash

# turtle : helper script to 
# make sure the PKGDEST folder is created by the builduser

BUILD_USER="builduser"
BUILD_DEST="/run/media/Packages"

function usb_err_(){
  echo "[-] USB drive is not present, stop."
  exit
}

#[[ ! -d "$BUILD_DEST" ]] && usb_err_

function build(){
  [[ -z "$@" ]] && return
  for PKG in "$@"; do
  sudo -u "$BUILD_USER" bash << EOF
    CURRENT=$PWD
    git clone https://aur.archlinux.org/$PKG.git
    cd $PKG
    #PKGDEST="$BUILD_DEST" makepkg -s --noconfirm
    cd $CURRENT
EOF
  done
}

function install(){
  [[ -z "$@" ]] && return
  for PKG in "$@"; do
    [[ "$(find "$BUILD_DEST" -iname "*$PKG*" -exec stat {} \;)" ]] && echo "Successfully installed $PKG" || echo "Could not find $PKG"
    #find "$BUILD_DEST" -iname "*$PKG*" -exec pacman -U {} \;
  done
}

build lightdm-slick-greeter
