#!/usr/bin/env bash

# Configure user applications such as the terminal, shell, etc

source user_configuration

function terminal_configuration() {
    pacman -Syu

    # ZSH #

    declare -a zsh_packages=(
        "zsh-completions"
        "zsh-syntax-highlighting"
    )
    printf "%s\n" "$MINT_PASS" | sudo --stdin -u "$MINT_USER" bash << EOF
    yay -S --noconfirm oh-my-zsh-git
    cp -v $MINT_HOME/Projects/dotfiles/shell/zshrc $MINT_HOME/.zshrc
EOF
    for zsh_package in "${zsh_packages[@]}"; do
        pacman -S --noconfirm "$zsh_package"
    done

    # VIM #

    pacman -S --noconfirm gvim cmake
    declare -a coc_extensions=(
        "coc-clangd"
        "coc-css"
        "coc-html"
        "coc-json"
        "coc-python"
        "coc-rust-analyzer"
        "coc-tsserver"
    )

  printf "%s\n" "$MINT_PASS" | sudo --stdin -u "$MINT_USER" bash << EOF
    yay -S --noconfirm vim-plugin
    cp -v assets/.vimrc $MINT_HOME
    vim +silent +PluginInstall +qall
    for extension in "${coc_extensions[@]}"; do
        vim +silent +"CocInstall $extension"
    done

    cp -v assets/coc-settings.json  $MINT_HOME/.vim
EOF

    # URXVT CONF #

    declare -a terminal_packages=(
        "powerline"
        "powerline-font"
        "rxvt-unicode"
        "ttf-dejavu"
        "xorg-xrdb"
    )
    for terminal_package in "${terminal_packages[@]}"; do
        pacman -S --noconfirm "$terminal_package"
    done

    printf "%s\n" "$MINT_PASS" | sudo --stdin -u "$MINT_USER" bash << EOF

    cp -v assets/.Xresources $MINT_HOME
    # this needs to be run in a X11 environmement!
    xrdb "$MINT_HOME"/.Xresources
EOF

    # GIT CONF # 

    printf "%s\n" "$MINT_PASS" | sudo --stdin -u "$MINT_USER" bash << EOF

    git config --global user.name "Jared Dyreson"
    git config --global user.email "jared.dyreson@gmail.com"
EOF
}
