#!/usr/bin/env bash

# Configure user profile

# Setup logging

LOG_DIR="/root/thin_mint_logs"

[[ ! -d "$LOG_DIR" ]] && mkdir "$LOG_DIR"

exec 1> >(tee "$LOG_DIR/user_configuration_stdout.log")
exec 2> >(tee "$LOG_DIR/user_configuration_stderr.log")


[[ ! -z "${USER_PLAIN+x}" ]] && export USER_PLAIN="jared"
[[ ! -z "${PASSWORD_PLAIN+x}" ]] && export PASSWORD_PLAIN="password"
MINT_HOME="/home/$USER_PLAIN"

## "Exceptions" ##

function perm_err_() {
    >&2 echo "[ERROR] Run as root, stop."
    exit 1
}

function no_user_specified_() {
    >&2 echo "[ERROR] No user specified, stop"
    exit 1
}

function user_exists_() {
    >&2 echo "[WARNING] $USER_PLAIN is already a user, skipping this step"
}

function wrong_os_err_() {
    >&2 echo "[ERROR] Only supports Arch Linux, stop"
    exit 1
}

## Functions ##

function make_root() {
    # Create allow our user to be apart of the sudoers group

    local M_USER="$1"

    echo "[INFO] Enabling user with name of: $M_USER to be apart of the sudoers group"

    [[ -z "$@" ]] && no_user_specified_
    echo "$M_USER ALL=(ALL) ALL" >> /etc/sudoers
    echo "COMPLETE"
}

function password_manager() {
    # Obtain the root password for the default user
    
    PASSONE=""
    PASSTWO="empty_password_please_fill"

    while [[ -z "$PASSONE" || "$PASSONE" != "$PASSTWO" ]]; do
        PASSONE=$(dialog --stdout --passwordbox "Enter admin password" 0 0) || exit 1
        clear
        PASSTWO=$(dialog --stdout --passwordbox "Enter admin password again" 0 0) || exit 1
        clear
    done

    echo "$USER_PLAIN:$PASSONE" | chpasswd "$USER_PLAIN"
    echo "root:$PASSONE" | chpasswd root
    export PASSWORD_PLAIN="$PASSONE" # this will be used throughout the lifetime of the script
}

function create_user() {
    [[ -z "${USER_PLAIN+x}" ]] && no_user_specified_ || echo "[INFO] Creating user of name: $USER_PLAIN"

    [[ "$(grep "^$USER_PLAIN" /etc/passwd)" ]] && user_exists_ || useradd -m -g users -G wheel,storage,power -s /bin/zsh "$USER_PLAIN"
    
    [[ -z "${PASSWORD_PLAIN+x}" ]] && password_manager

    printf "%s\n" "$PASSWORD_PLAIN" | sudo --stdin -u "$USER_PLAIN" bash << EOF
    mkdir -pv $MINT_HOME/{Applications,Downloads,Documents,Music,Pictures/{screenshots,Wallpapers},Projects,Videos}
EOF

    make_root "$USER_PLAIN"
}

function initial_configuration() {
    # Create a build and regular user

    [[ -f /var/lib/pacman/db.lck ]] && rm /var/lib/pacman/db.lck  
    # NOTE: removed installation candidates here, moved them to the base_install

    #if [[ ! $(grep "^builduser" /etc/passwd) ]]; then
        #echo "[INFO] Creating builduser"
        ##useradd -s /bin/bash builduser -m
        ##passwd -d builduser
        ##make_root builduser
    #else
        #echo "[INFO] BUILDUSER EXISTS"
    #fi
    echo "[INFO] Before creating user" 
    create_user
    # we changed this from building from source 
    echo "[INFO] Installing yay"

    sudo -u "builduser" bash << EOF
    sudo pacman -S --needed git base-devel
    git clone https://aur.archlinux.org/yay-bin.git /home/$USER_PLAIN/yay
    cd /home/$USER_PLAIN/yay
    makepkg -si --noconfirm
EOF

}
initial_configuration
