#!/usr/bin/env bash

source turtle
source user_configuration

function application_installer(){
  pacman -Sy --noconfirm vlc zenity firefox htop bluez blueman file-roller xreader virtualbox gedit discord gnome-calculator
  install spotify ffmpeg-compat-57 shutter mintstick pix slack

  printf "%s\n" "$MINT_PASS" | sudo --stdin -u "$MINT_USER" bash << EOF
    cp -arv --no-preserve=mode "$USB_BASE"/firefox_data/* "$MINT_HOME"/.mozilla/
    chown -R "$MINT_USER":users "$MINT_HOME"/.mozilla
    xdg-mime default xreader.desktop application/pdf   
EOF

}

application_installer
