#!/usr/bin/env bash

function latex_install() {

    declare -a packages=(
        "pandoc"                    # converting between different file formats
        "texlive-bibtexextra"       # bibliographies
        "texlive-core"              # core distribution
        "texlive-formatsextra"      # TeX formats
        "texlive-latexextra"        # extra addons
        "texlive-pictures"          # rendering pictures
        "texlive-science"           # computer sience stuff
    )

    pacman -Syu

    for package in "${packages[@]}"; do
        pacman -S --noconfirm "$package"
    done

}
