#!/usr/bin/env zsh

function cinnnmon_de() {
    # This is a floating window manager

    USB_PATH="/run/media/$MINT_USER/"

    declare -a packages=(
        "cinnamon"
        "file-roller"
        "noto-fonts"
        "xorg-server"
    )

    pacman -Syu

    for package in "${packages[@]}"; do
        pacman -S --noconfirm "$package"
    done
}

function i3_configuration() {
    echo "PLEASE IMPLEMENT ME"
}
