#!/usr/bin/env bash

# install and configure utilities that interact with iPhones
# original documents from the Arch Wiki -> https://wiki.archlinux.org/index.php/User:Lekensteyn/Upgrading_iOS

exec 1> >(tee "iphone_setup_stdout.log")
exec 2> >(tee "iphone_setup_stderr.log")

[[ "$(whoami)" != "root" ]] && not_root_

function not_root_(){
  >&2 echo "[-] You need to run this script as root"
  exit
}

sudo pacman -Sy ifuse usbmuxd libplist libimobiledevice
mkdir ~/iPhone

echo "[+] Please consult the README for further details"
