#!/usr/bin/env bash

# install and configure utilities that interact with iPhones
# original documents from the Arch Wiki -> https://wiki.archlinux.org/index.php/User:Lekensteyn/Upgrading_iOS

exec 1> >(tee "iphone_setup_stdout.log")
exec 2> >(tee "iphone_setup_stderr.log")

[[ "$(whoami)" != "root" ]] && not_root_

function not_root_(){
  >&2 echo "[-] You need to run this script as root"
  exit
}

function install_libirecovery(){
  git clone https://github.com/libimobiledevice/libirecovery.git
  sudo ./autogen.sh --prefix=/usr
  sudo make && sudo make install
}
function install_libimobiledevice(){
  git clone https://github.com/libimobiledevice/libimobiledevice.git
  sudo ./autogen.sh --prefix=/usr
  sudo make && sudo make install
}

function install_idevicerestore(){
  git clone https://github.com/libimobiledevice/idevicerestore.git
  sudo ./autogen.sh --prefix=/usr
  sudo make && sudo make install
}

sudo pacman -Sy --noconfirm ifuse usbmuxd libplist libzip
install_libirecovery && install_libimobiledevice && install_idevicerestore
mkdir ~/iPhone

echo "[+] Please consult the README for further details"
