#!/usr/bin/env bash

# install and configure utilities that interact with iPhones
# original documents from the Arch Wiki -> https://wiki.archlinux.org/index.php/User:Lekensteyn/Upgrading_iOS

exec 1> >(tee "iphone_setup_stdout.log")
exec 2> >(tee "iphone_setup_stderr.log")

function not_root_(){
  >&2 echo "[-] You need to run this script as root"
  exit
}

[[ "$(whoami)" != "root" ]] && not_root_

function clone_repos() {
    git clone https://github.com/libimobiledevice/libplist
    git clone https://github.com/libimobiledevice/libusbmuxd
    git clone https://github.com/libimobiledevice/libimobiledevice
    git clone https://github.com/libimobiledevice/usbmuxd
}

function libplist() {
    cd libplist
    ./autogen.sh
    make && sudo make install
    sudo ldconfig
    cd ..
}

function libusbmuxd() {
    cd libusbmuxd
    PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./autogen.sh
    make && sudo make install
    sudo ldconfig
    cd ..
}

function libimobiledevice() {
    cd libimobiledevice
    PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./autogen.sh --enable-debug
    make && sudo make install
    cd ..
}

function usbmuxd() {
    cd usbmuxd
    PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./autogen.sh --prefix=/usr --sysconfdir=/etc --localstatedir=/var --runstatedir=/run
    make && sudo make install
    sudo killall usbmuxd
}

function clean_up() {
    rm -fr libplist/ libusbmuxd/ libimobiledevice/ usbmuxd/
}

function all() {
    clone_repos
    libplist
    libusbmuxd
    libimobiledevice
    usbmuxd
    clean_up
}

sudo pacman -Sy --noconfirm ifuse libzip

all

mkdir ~/iPhone

echo "[+] Please consult the README for further details"
