#!/usr/bin/env bash

# installer script for Arch Linux (1/4)
# task: setup partitions, internet, and install base packages 
# AUTHOR: Jared Dyreson

exec 1> >(tee "$LOG_DIR/base_install_stdout.log")
exec 2> >(tee "$LOG_DIR/base_install_stderr.log")

# base disk, amount of memory installed, and swap size

TGTDEV="$(lsblk -dplnx size -o name,size | grep -Ev "boot|rpmb|loop" | tail -n 1 | awk '{print $1}')"
MEMORY_INSTALLED="$(awk '/MemTotal/ {$2=$2/(1024^2); print int($2+0.5)}' /proc/meminfo)"

# set the default size to twice the amount of RAM
#[[ ! -z "${SWAP_SIZE+x}" ]] && 
SWAP_SIZE="$(echo "$(($MEMORY_INSTALLED * 2))")" 
[[ ! -z "${ROOT_PARTITION_SIZE+x}" ]] && ROOT_PARTITION_SIZE=40 # set to the default size of 40 GBs

function partition() {
    # Give each partition their amount of space

    local SWAP="$1"
    local ROOT="$2"

    sed -i "s/\[SWAP_SIZE\]/$SWAP/;s/\[ROOT_SIZE\]/$ROOT/" assets/fdisk_script
    sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' assets/fdisk_script | fdisk "${TGTDEV}"
}

function wifi_menu_configuration() {
    # Configure WiFi

    WIRELSS_INTERFACE="$(ip link | awk '/mtu/ {print $2}' | cut -d: -f1 | grep "wlp*")"
    systemctl enable netctl-auto@"$WIRELSS_INTERFACE".service
    wifi-menu -o
}

function unmount_all_partitions() {
    umount /mnt/boot
    umount /mnt/home
    umount /mnt/
}

function hostname_configuration() {
    local HOST="$1"

    sed "s/\[HOSTNAME\]/$HOST/" assets/host > /mnt/etc/hosts
}

timedatectl set-ntp true

# Partition names


# sub partitions

EFI=""$TGTDEV"1"
SWAP=""$TGTDEV"2"
ROOT=""$TGTDEV"3"
HOME=""$TGTDEV"4"

# drop all partitions but data is still intact

dd if=/dev/zero of="$TGTDEV" bs=512 count=1

# partitioning the drives
echo "[INFO] Swap is: $SWAP_SIZE"
echo "[INFO] Root is: $ROOT_PARTITION_SIZE"

partition "$SWAP_SIZE" "$ROOT_PARTITION_SIZE"

# make the EFI partition, swap (enable as well), root and user partitions

mkfs.vfat -F32 "$EFI"
mkswap "$SWAP"
swapon "$SWAP"
mkfs.ext4 "$ROOT"
mkfs.ext4 "$HOME"

# mount and make new partitions

mount --verbose "$ROOT" /mnt
mkdir /mnt/{boot,home}
mount --verbose "$EFI" /mnt/boot
mount --verbose "$HOME" /mnt/home

# internet and check if the script is running inside a VM

[[ "$(grep "hypervisor" /proc/cpuinfo))" ]] && echo "[+] Using builtin internet" || wifi_menu_configuration

# install the bare minimum packages

declare -a essential_packages=(
    "base"
    "base-devel"
    "bluez"
    "cryptsetup"
    "device-mapper"
    "dialog"
    "e2fsprogs"
    "git"
    "inetutils"
    "intel-ucode"
    "linux"
    "linux-firmware"
    "man-db"
    "man-pages"
    "networkmanager"
    "python"
    "s-nail"
    "sudo"
    "sysfsutils"
    "usbutils"
)

for package in "${essential_packages[@]}"; do
    pacstrap /mnt "$package"
done

# setup fstab so we know where we can boot from

genfstab -U /mnt >> /mnt/etc/fstab

# we need to lead into the chroot environment from here

# make sure this name is reflected in our network configuration

# what is our machine's name to the world

[[ ! -z "${HOSTNAME+x}" ]] && HOSTNAME=""$USER_PLAIN"-computer"

hostname_configuration "$HOSTNAME"

cp -v chroot_env /mnt
cp -v assets/startup.nsh /mnt/boot
echo "$HOSTNAME" > /mnt/etc/hostname

cat /mnt/etc/hosts
cat /mnt/etc/hostname

arch-chroot /mnt ./chroot_env
