#!/usr/bin/env bash

# this file contains definitions of functions and  can be used in another script
# please refer to importing_hello for usage

a=100
b=10

function hello_world(){
  echo "This is a test from hello!"
}

function using_arguments(){
  [[ -z "$@" ]] && return
  echo "The value of the argument is $1"
}
