#!/usr/bin/env bash

# configure the battery

function err_(){
  >&2 echo "[+] You are not root, cowardly refusing to configure battery"
  exit 1
}

function battery(){
  lscpi | grep -i nvme && pacman -Sy --noconfirm nvme-cli tlp || pacman -Sy --noconfirm tlp
  sudo systemctl enable tlp.service tlp-sleep.service
  echo "[+] Enabling TLP Services"
}

[[ "$(whoami)" != "root" ]] && err_ || battery
